### ISSUE TITLE
[Modules]: add examples/modules on the most uses services/images

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#636]
### Proposal

Given there is a tool to generate the scaffolding for new examples as Go modules (https://golang.testcontainers.org/examples), let's use it to start adding examples.

We have elaborated the list below from Testcontainers for Java. If you're interested in adding any example, please comment here the module you want to work on (we'll add your username to next to it in the list), use the tool to generate the scaffolding for the module you are interested in, and send a PR. We'll link your PR here next to the item in the list.

Our recommendation is to visit the Java module and start porting its behavior and settings to the Go example module.

## Modules
- [ ] azure cosmosdb
- [x] cassandra @anilsenay #1726
- [x] clickhouse @anilsenay https://github.com/testcontainers/testcontainers-go/pull/1372
- [x] cockroachdb @mdelapenya #618
- [x] consul @bo-er https://github.com/testcontainers/testcontainers-go/pull/722 @Chris-AS1 https://github.com/testcontainers/testcontainers-go/pull/2194
- [x] @alihanyalcin #932 https://github.com/testcontainers/testcontainers-go/pull/876
- [ ] db2
- [ ] dragonflydb
- [ ] dynalite
- [x] elasticsearch @mdelapenya https://github.com/testcontainers/testcontainers-go/pull/1574
- [x] gcloud
  - [x] datastore @eddumelendez https://github.com/testcontainers/testcontainers-go/pull/638
  - [x] firestore @eddumelendez https://github.com/testcontainers/testcontainers-go/pull/637
  - [x] pubsub @eddumelendez https://github.com/testcontainers/testcontainers-go/pull/640
  - [x] spanner @eddumelendez https://github.com/testcontainers/testcontainers-go/pull/642
- [ ] hivemq
- [x] inbucket @jespino #2142
- [x] influxdb
- [x] k3s @mritunjaysharma394 #1194 
- [x] k6 @pablochacin https://github.com/testcontainers/testcontainers-go/pull/1721
- [x] kafka @noctarius https://github.com/testcontainers/testcontainers-go/pull/1610
- [x] localstack @mdelapenya #795
- [x] mariadb @mdelapenya #1548
- [x] minio @adoublef  https://github.com/testcontainers/testcontainers-go/pull/2132
- [x] mockserver @jespino https://github.com/testcontainers/testcontainers-go/pull/2085
- [x] mongodb @ravilushqa #723 and #726
- [x] mssqlserver @agosmou #1969
- [x] mysql @mdelapenya #700 @eddumelendez #943 
- [x] nats @adoublef https://github.com/testcontainers/testcontainers-go/pull/1190 @mdelapenya https://github.com/testcontainers/testcontainers-go/pull/1559
- [x] neo4j @fbiville #921
- [x] nginx @mdelapenya #618 
- [x] openldap @jespino https://github.com/testcontainers/testcontainers-go/pull/2117
- [ ] oracle-xe
- [ ] orientdb
- [x] postgresql @mdelapenya #674 https://github.com/testcontainers/testcontainers-go/pull/945
- [ ] presto
- [x] pulsar @mdelapenya #618
- [ ] questdb
- [x] rabbitmq @mdelapenya #1618 @Tingaev #1031 
- [x] redis  @mdelapenya #618
- [x] redpanda @weeco #1058
- [ ] selenium
- [ ] solr
- [ ] tidb
- [x] toxiproxy @eddumelendez https://github.com/testcontainers/testcontainers-go/pull/643
- [ ] trino
- [x] vault @alihanyalcin https://github.com/testcontainers/testcontainers-go/pull/942
- [ ] yugabytedb

**Comment by ravilushqa** [comment]
@mdelapenya can I pick mongodb?

**Comment by mdelapenya** [comment]
> @mdelapenya can I pick mongodb?

Please do it! 🙏

**Comment by fbiville** [comment]
Interested in tackling Neo4j :)

**Comment by mdelapenya** [comment]
> Interested in tackling Neo4j :)

@fbiville Amazing! Please do it, and thanks for your support :)

**Comment by Tingaev** [comment]
@mdelapenya can I pick RabbitMQ?

**Comment by mdelapenya** [comment]
> @mdelapenya can I pick RabbitMQ?

@Tingaev please go for it! Do you want to create an example or a real Go module? We should probably communicate the difference in a clearer manner, but modules for designed as dependencies to be consumed by downstream project, and examples for simply demonstrations, copying the code snippets, which include private APIs. Whatever you prefer is welcome

**Comment by Tingaev** [comment]
> Do you want to create an example or a real Go module?
@mdelapenya I thought and decided to make a module instead of just an example
I will close the PR with an example

**Comment by mdelapenya** [comment]
> > Do you want to create an example or a real Go module?
> 
> @mdelapenya I thought and decided to make a module instead of just an example I will close the PR with an example

@Tingaev please take a look at https://github.com/testcontainers/testcontainers-go/pull/1016/files#diff-bf2f2ea9f93d17fd1a016e2893c5b7fe7dae04263b1662c8e03926e4e728f495. In this PR we try to explain how to create it

**Comment by adoublef** [comment]
I would be keen to including a NATS example (possibly module in the future) what would be required to do so?

**Comment by eddumelendez** [comment]
@adoublef you can probably start with a NATS example similar to what we have in `Testcontainers for Java`, see [this](https://github.com/testcontainers/testcontainers-java/blob/main/examples/nats/src/test/java/com/example/NatsContainerTest.java). If you know more about NATS and how Testcontainers can help then we are all ears to build a NATS module.

**Comment by adoublef** [comment]
@eddumelendez cool, I have been in the slack groups for a while & been learning how to use NATS personally so will be able to showcase a usage. I also know from the NATS slack group, a lot are using jetstream.

I could likely port [this](https://github.com/adoublef/noughts-and-crosses/blob/main/pkg/containers/nats_container.go) over as I have found myself being able to get this working on many small projects

**Comment by mdelapenya** [comment]
@adoublef I'd suggest starting with an example is great for experimenting with a module, like an incubation stage. Once you are happy with it, you could convert it into a real module, as described in https://golang.testcontainers.org/modules

You could use the code generation tool to bootstrap the scaffolding, and/or migrate the existing example following this:
- File structure: https://golang.testcontainers.org/modules/#interested-in-converting-an-example-into-a-module
- Types and exposed functions/methods: https://golang.testcontainers.org/modules/#adding-types-and-methods-to-the-module

Please consider that the modules design is still in dev (see https://github.com/testcontainers/testcontainers-go/pull/1042) so it's evolving using proper, better abstractions in it.

**Comment by mritunjaysharma394** [comment]
Hi @mdelapenya, I am interested for k3s, can i pick iit up :))

Thanks!

**Comment by mdelapenya** [comment]
@mritunjaysharma394 be my guest and do it! There is a Java implementation you can follow (j terms of API), will post here a link to it as I'm AFK

**Comment by mritunjaysharma394** [comment]
That was quick, thanks a lot @mdelapenya, I guess you meant this [link](https://github.com/testcontainers/testcontainers-java/tree/main/modules/k3s) right? 

also, loving this [blog](https://www.atomicjar.com/2023/05/creating-modules-in-testcontainers-go/) by you already!

**Comment by adoublef** [comment]
I wanted to request adding a minio module?

**Comment by mdelapenya** [comment]
I'm going to close this issue, as the modules catalog has grown a lot, and I think we do not need to track them all here.

Thank you all for your work creating modules!
